### ISSUE TITLE
Financial or non-financial?

### ISSUE THREAD

**Issue by SidVal** [machinomy/awesome-non-financial-blockchain#1]
Hello.

I can't understand why a blochchain project is "financial" or "non-financial".
Can you explain it please?

Example:
>21 - Micropayments for HTTP API over BitCoin payment channels, and library for IoT applications

For me, that project is financial.

**Comment by ukstv** [comment]
Awesome question, @SidVal 

Added justification below to the README.

Industry of a blockchain application is defined by the one that is changed the most. For example, discontinued IoT bitcoin micropayments startup [21](https://21.co) could significantly change both IoT and Financial sectors. Financial industry would expand its _current_ practice to a new domain. For IoT, however, _business model_ would change significantly. That intuition commands current classification.

What do you think?

**Comment by SidVal** [comment]
Thank you @ukstv, now I've a better understanding 
I Close this issue.

See you next time!

**Comment by ukstv** [comment]
Thank you so much!
